FROM mysql:8.0-debian

RUN apt-get update && apt-get -y install locales locales-all

RUN locale-gen ja_JP.UTF-8
RUN update-locale LANG=ja_JP.UTF-8

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8

COPY data/conf.d/my.cnf /etc/mysql/conf.d/

EXPOSE 3306